[package]
name = "pg-test-utilities"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1.34" }
sqlx = { version = "0.6", features = ["postgres"], default-features = false }
url = "2.3.1"
thiserror = "1.0.38"
